server:
  port: ${PORT:8080}

spring:
  application:
    name: server
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/texttolearn}
      database: ${MONGODB_DATABASE:texttolearn}
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

google:
  client-id: ${GOOGLE_CLIENT_ID}

youtube:
  api:
    key: ${YOUTUBE_API_KEY:AIzaSyCFeZRmMfh83YQ49QC2jZ06r71ecsWF7cA}

rabbitmq:
  exchange: ${RABBITMQ_EXCHANGE:texttolearn.exchange}
  queue: ${RABBITMQ_TOPIC_QUEUE:texttolearn.queue}
  routing-key: "topic.#"

app:
  cors:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:5173}
